### ISSUE TITLE
Cannot invoke "Object.equals(Object)" because the return value of "org.hipparchus.geometry.partitioning.BSPTree.getAttribute()" is null

### ISSUE THREAD

**Issue by Sohnny0** [Hipparchus-Math/hipparchus#314]
I got a null pointer exception when I ran the code below. I guess it's a minor bug.

try {
    intersection = (SphericalPolygonsSet) factory.intersection(zone.copySelf(), targetSphericalPolygonsSet.copySelf());
} catch (Exception e) {
    e.printStackTrace();
}

java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.hipparchus.geometry.partitioning.BSPTree.getAttribute()" is null
	at org.hipparchus.geometry.partitioning.RegionFactory$VanishingToLeaf.fixNode(RegionFactory.java:381)
	at org.hipparchus.geometry.partitioning.BSPTree.insertInTree(BSPTree.java:680)
	at org.hipparchus.geometry.partitioning.RegionFactory$IntersectionMerger.merge(RegionFactory.java:267)
	at org.hipparchus.geometry.partitioning.BSPTree.merge(BSPTree.java:437)
	at org.hipparchus.geometry.partitioning.BSPTree.merge(BSPTree.java:455)

**Comment by maisonobe** [comment]
Could you set up a standalone test case allowing to reproduce the issue?

**Comment by Sohnny0** [comment]
> Could you set up a standalone test case allowing to reproduce the issue?

I have been busy recently, so I have solved it in this way for the time being. I will provide test cases later when I have time.

        public BSPTree<S> fixNode(final BSPTree<S> node) {
            Object attribute = node.getPlus().getAttribute();
            if (attribute != null && attribute.equals(node.getMinus().getAttribute())) {
                // no ambiguity
                return new BSPTree<S>(node.getPlus().getAttribute());
            } else {
                // ambiguous node
                return new BSPTree<S>(inside);
            }
        }
