### ISSUE TITLE
Avoid  exception "org.hipparchus.exception.MathIllegalArgumentException: matrix is singular" for complex implementations

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#337]
Can the exception `org.hipparchus.exception.MathIllegalArgumentException: matrix is singular` also be avoided for the "Complex implementations" `ComplexEigenDecomposition` and `OrderedComplexEigenDecomposition`?
```
@Test
  public void testEqualEigenValuesSingular() {
    Array2DRowRealMatrix matrix =
        new Array2DRowRealMatrix(new double[][] {{1, 0, 0}, {-2, 1, 0}, {0, 1, 1}});
    EigenDecompositionNonSymmetric ed = new EigenDecompositionNonSymmetric(matrix);
    for (int i = 0; i < 3; i++) {
      System.out.println(ed.getEigenvector(i));
    }

    try {
      ComplexEigenDecomposition complexEigenDecomposition = new ComplexEigenDecomposition(matrix);
      for (int i = 0; i < 3; i++) {
        System.out.println(complexEigenDecomposition.getEigenvector(i));
      }
    } catch (MathRuntimeException mre) {
      mre.printStackTrace();
    }

    try {
      ComplexEigenDecomposition ced = new OrderedComplexEigenDecomposition(matrix, //
          ComplexEigenDecomposition.DEFAULT_EIGENVECTORS_EQUALITY, //
          ComplexEigenDecomposition.DEFAULT_EPSILON, //
          ComplexEigenDecomposition.DEFAULT_EPSILON_AV_VD_CHECK, //
          (c1, c2) -> Double.compare(c2.norm(), c1.norm()));
      for (int i = 0; i < 3; i++) {
        System.out.println(ced.getEigenvector(i));
      }
    } catch (MathRuntimeException mre) {
      mre.printStackTrace();
    }
  }
```

See:
- https://github.com/axkr/symja_android_library/issues/979

**Comment by axkr** [comment]
This input:
```mma
Eigenvalues({{1,0,0,0,0},{3,1,0,0,0},{6,3,2,0,0},{10,6,3,2,0},{15,10,6,3,2}})
```

raises a "failed decomposition of a 5x5 matrix" exception:
```java
org.hipparchus.exception.MathRuntimeException: failed decomposition of a 5x5 matrix
	at org.hipparchus.linear.ComplexEigenDecomposition.checkDefinition(ComplexEigenDecomposition.java:455)
	at org.hipparchus.linear.ComplexEigenDecomposition.<init>(ComplexEigenDecomposition.java:167)
	at org.hipparchus.linear.OrderedComplexEigenDecomposition.<init>(OrderedComplexEigenDecomposition.java:98)
	at org.matheclipse.core.builtin.LinearAlgebra$Eigenvalues.realMatrixEval(LinearAlgebra.java:2204)
```

**Comment by maisonobe** [comment]
I confirm the problem.
Already worked a few hours on it. I am still invetigating.
