### ISSUE TITLE
Recursion intended in LegendreRuleFactory.java?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#61]
See also this issue:
- https://github.com/axkr/symja_android_library/issues/150

For `numberOfPoints = 10000` a `StackOverflowError`  was created.

- https://github.com/Hipparchus-Math/hipparchus/blob/ae239317bbc9e268d0db5ae72a4ba3a581a1492c/hipparchus-core/src/main/java/org/hipparchus/analysis/integration/gauss/LegendreRuleFactory.java#L51

- https://github.com/Hipparchus-Math/hipparchus/blob/ae239317bbc9e268d0db5ae72a4ba3a581a1492c/hipparchus-core/src/main/java/org/hipparchus/analysis/integration/gauss/BaseRuleFactory.java#L101

Does it make sense to check a maximum value for `numberOfPoints`?

```Java
java.lang.StackOverflowError
	at java.lang.Number.<init>(Number.java:55)
	at java.lang.Integer.<init>(Integer.java:849)
	at java.lang.Integer.valueOf(Integer.java:832)
	at org.hipparchus.analysis.integration.gauss.BaseRuleFactory.getRuleInternal(BaseRuleFactory.java:99)
	at org.hipparchus.analysis.integration.gauss.LegendreRuleFactory.computeRule(LegendreRuleFactory.java:51)
	at org.hipparchus.analysis.integration.gauss.BaseRuleFactory.getRuleInternal(BaseRuleFactory.java:101)
	at org.hipparchus.analysis.integration.gauss.LegendreRuleFactory.computeRule(LegendreRuleFactory.java:51)
	at org.hipparchus.analysis.integration.gauss.BaseRuleFactory.getRuleInternal(BaseRuleFactory.java:101)
	at org.hipparchus.analysis.integration.gauss.LegendreRuleFactory.computeRule(LegendreRuleFactory.java:51)
```

**Comment by maisonobe** [comment]
You are right.

I confirm the bug and your fix about checking the number of points. I will try to find a proper limit value.
